### ISSUE TITLE
Howto route a network behind a client/peer?

### ISSUE THREAD

**Issue by majes-github** [EmbarkStudios/wg-ui#100]
Hello,

I don't see an option to specify a network behind a wireguard client. Normally that should be possible using "allowed ips".

Please advise.

**Comment by suom1** [comment]
You can specify the allowed ips with `--wg-allowed-ips=` when running wg-ui! 
You can find documentation about flags by running adding `-h` when running the binary.

**Comment by majes-github** [comment]
Of course I have tested `--wg-allowed-ips` before posting. This options adds `AllowedIPs =` to all **clients**!

I'm looking for an equivalent of this server config in wg-quick syntax:

```
# the server
[Interface]
PrivateKey = XXXX
Address = 172.16.0.1/32
ListenPort = 51820

# client A
[Peer]
PublicKey = YYYY
AllowedIPs = 172.16.0.11/32, 192.168.178.0/24


# client B
[Peer]
PublicKey = ZZZZ
AllowedIPs = 172.16.0.12/32, 192.168.0.0/24
```

**Comment by suom1** [comment]
Ah, I misunderstood. 
That's not currently supported.

**Comment by majes-github** [comment]
Too bad. Unfortunately, this makes this very nice tool useless to me. Shouldn't be a big feature to implement, since the server already sets `AllowedIPs` to the tunnel IP of the particular client. Adding another subnet (taken from a UI string field) should be rather simple.
How big are chances to get this merged when I would provide a PR?

**Comment by suom1** [comment]
We gladly merge a change for it, feel free to submit a PR!
