### ISSUE TITLE
No networking to docker?

### ISSUE THREAD

**Issue by Cr0iX** [EmbarkStudios/wg-ui#101]
When i run wgui with this command: 
docker run --rm -it --privileged --entrypoint "/wireguard-ui" -v /tmp/wireguard-ui:/data -p 56561:56561 -p 51322:51322 embarkstudios/wireguard-ui:latest --data-dir=/data --wg-listen-port=51322 --wg-dns="172.16.1.16" --listen-address="127.0.0.1:56561" --log-level=debug

and then i try to get access to the webinterface i cant:
curl http://127.0.0.1:56561
curl: (56) Recv failure: Connection reset by peer

**Expected behavior**
To have access to the webinterface

**Device:**
 - OS: Centos 8 / apache
 - Browser curl/chrome

Hope you can help me with what im doing wrong.

**Comment by suom1** [comment]
I can see now that I have forgotten to answer this. But to solve this remove 127.0.0.1 from ` --listen-address="127.0.0.1:56561"` leaving it like this ` --listen-address=":56561"` and it will work. (verified locally for me)
