### ISSUE TITLE
[Help/Advice] Feature extensions

### ISSUE THREAD

**Issue by omar391** [EmbarkStudios/wg-ui#103]
Dear maintainers,

I need the following features:

- Bandwidth controlling
- Split tunneling
- Data Limit per month basis
- User/peer registration and auto-config generation
- HTTP request caching via reverse proxy

Which of these features are available or which can be integrated via GO code?

**Comment by suom1** [comment]
> * Bandwidth controlling
Not supported, and unaware if there is support for this in WireGuard.

> * Split tunneling
Whether you want your wg-ui instance to use split tunneling or send all traffic through the tunnel you do this configuration with AllowedIPs and then depending on if you want to push a default gateway you configure NAT on the machine running wireguard (server).

> * Data Limit per month basis
This is not supported

> * User/peer registration and auto-config generation
Not sure what you're asking for here, but when you create a new config you get a generated config for you.

> * HTTP request caching via reverse proxy
This can be done many different ways, we at Embark Studios use a nginx infront of the webinterface to do this. 

> Which of these features are available or which can be integrated via GO code?
The ones not supported might be possible to integrate with additional code, however I am not sure if that's something that would be suitable for this project.
