### ISSUE TITLE
Synology DSM 6.2 - FATA[0000] socket: protocol not supported

### ISSUE THREAD

**Issue by christian-hoekstra** [EmbarkStudios/wg-ui#111]
Hi,

Great solution, looking forward using it! However I faced an issue.

Synology D416 Play (Intel based), Synology Docker Package.

Compiled and installed https://github.com/runfalk/synology-wireguard. Did not run any config. Just installed package to get the kernel module (your manual suggest this is enough). No wg0 device (or others) exist.

```
lsmod | grep -i wireguard
wireguard             167879  0
ip_tunnel              11456  3 sit,vxlan,wireguard
ipv6                  306497  189 ah6,sit,esp6,rodsp_ep,xfrm6_mode_beet,nf_defrag_ipv6,l2tp_core,xfrm6_tunnel,wireguard,xfrm6_mode_tunnel,ipcomp6,nf_conntrack_ipv6
```

When running slightly modified example command `docker run --rm -it --privileged --entrypoint "/wireguard-ui" -v /volume1/docker/containers/WireGuardUI/data:/data -p 8081:8081 -p 51820:51820 embarkstudios/wireguard-ui:latest --data-dir=/data --log-level=debug` I get tty output:

```
INFO[0000] Starting
DEBU[0000] ipAddr: 172.31.255.0  ipNet: 172.31.255.0/24
DEBU[0000] Read server config from file: /data/config.json
DEBU[0000] Configuration loaded with public key: <Removed the private key>
DEBU[0000] Server initialized: /data
DEBU[0000] Adding wireguard device: wg0
DEBU[0000] Adding ip address to wireguard device: 172.31.255.0/24
DEBU[0000] Bringing up wireguard device: wg0
DEBU[0000] Adding NAT / IP masquerading using nftables
DEBU[0000] Flushing nftable rulesets
DEBU[0000] Setting up nftable rules for ip masquerading
FATA[0000] socket: protocol not supported
```

Searching the internet did not provide any ideas. I am a WireGuard newbie, be gentle ;-)

Best Regards,

Christian (NL)

**Comment by suom1** [comment]
Sadly since we have no access to a synology device there is no way for us to even troubleshoot this. However looking at the error message I would say something is missing from the OS .
