### ISSUE TITLE
make build fails with `make: go-bindata-assetfs: Command not found`

### ISSUE THREAD

**Issue by tromlet** [EmbarkStudios/wg-ui#112]
**Describe the bug**
Install fails after the `make build` step with the following error message:
```bash
...
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js??ref--5-2!src/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-2!./src/style.scss 3.72 KiB {0} [built]
        + 1 hidden module
go get github.com/go-bindata/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go-bindata-assetfs -prefix ui/dist ui/dist
make: go-bindata-assetfs: Command not found
make: *** [assets] Error 127
```

**To Reproduce**
1. run `make build` or `make build-amd64`

**Expected behavior**
I expected the build process to complete successfully, and then to resume the README guide past the `make build` step.

**Screenshots**
n/a

**Device:**
 - OS: CentOS 7
 - Node.js v14.15.4
 - go 1.15.7
 - wg-ui 1.1.0

**Comment by ThatRandomDude** [comment]
Did you add `$HOME/go/bin` to your .bash_history and opened a new session?
Alternatively you could just export the new line in the current session.

Had this problem moments ago and thought it would be enough to add the global go path `/usr/local/go/bin`.

Go downloads the go-bindata-assetfs to `$HOME/go/bin`

**Comment by tromlet** [comment]
I did, as a matter of fact. Found that from another thread elsewhere on the net. I'm running as root, with `$GOBIN` equal to `/root/go/bin`. Still get that error. It doesn't seem like it fails to download... :/

**Comment by suom1** [comment]
I am pretty sure you either have wrong or missing `$GOPATH` or missing `$GOPATH/bin` from `$PATH`.
What's the output of this `echo $PATH && echo $GOPATH`?

**Comment by tromlet** [comment]
Oh that might be something. I don't know of `$GOPATH` is set!
```bash
[root@vpn ~]# echo $PATH && echo $GOPATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin

[root@vpn ~]# 
```

**Comment by suom1** [comment]
This issue is 100% related to your system not finding go-bindata-assetfs binary based on your environment variables. I am not able to reproduce this on my systems.

**Comment by tromlet** [comment]
I fixed it by adding `$GOPATH` (or, in my case, following the Go setup instructions, `$GOBIN`) to my `$PATH` in `~/.bash_profile`.

```text
# Add Go to PATH
export GOBIN=$HOME/go/bin
export PATH=$PATH:/usr/local/go/bin:$GOBIN
```
