### ISSUE TITLE
Integrate a wireguard mesh configurator w WireGuard- UI

### ISSUE THREAD

**Issue by bmullan** [EmbarkStudios/wg-ui#15]
Have you thought about this as no one else has (yet)?

Here are 3 I've seen...

k4yt3x/wireguard-mesh-configurator: WireGuard full mesh configuration generator.

https://github.com/k4yt3x/wireguard-mesh-configurator

costela/wesher: wireguard overlay mesh network manager

https://github.com/costela/wesher

One I like so far...

m13253/VxWireguard-Generator: Utility to generate VXLAN over Wireguard mesh SD-WAN configuration

https://github.com/m13253/VxWireguard-Generator

**Comment by suom1** [comment]
As `wg-ui` is built more for end users and their VPN profiles we do not have any plans on implementing site-to-site or mesh configuration into `wg-ui`.
