### ISSUE TITLE
unable to use goauthentik proxy

### ISSUE THREAD

**Issue by ks32** [EmbarkStudios/wg-ui#171]
After successful goauthentik  authentication, wg-ui shows same Logged in as anonymous.
Is there any other configuration?

my setup is authentik (goauthentik.io) and NPM (Nginx Proxy Manager).

**Comment by mono-of-pg** [comment]
Did you set the auth-user-header option?
`--auth-user-header="X-Authentik-Username"`

**Comment by ks32** [comment]
following is added in NPM
    proxy_set_header X-authentik-username $authentik_username;

**Comment by mono-of-pg** [comment]
> following is added in NPM proxy_set_header X-authentik-username $authentik_username;

you also have to tell wg-ui which header to look for using the option i mentioned in my last comment.

**Comment by ks32** [comment]
okay got it. Added following in docker-compose
entrypoint: '/wireguard-ui --auth-user-header="X-Authentik-email"'

It is working now.
