### ISSUE TITLE
FATA[0000]

### ISSUE THREAD

**Issue by Kawabountou** [EmbarkStudios/wg-ui#36]
hi,

when i build the docker, all it's ok
docker build . -t xxx/wireguard-ui

but when i run the docker, it's failled.
docker run --rm -it --privileged --entrypoint "/wireguard-ui" -v /tmp/wireguard-ui:/data -p 8080:8080 -p 5555:5555 xxx/wireguard-ui --data-dir=/data --log-level=debug

FATA[0000] operation not supported

when i run the original command, it's failled so

Romain

**Comment by freddd** [comment]
Hi @Kawabountou,

Thanks for creating an issue. What OS are you using? Do you have wireguard installed on the host?

Thanks

**Comment by Kawabountou** [comment]
I use Debian 10, on adm64.
I have no wireguard installed on my debian.
I only run the docker, in the terminal

**Comment by freddd** [comment]
This is just a ui for wireguard and does not install wireguard itself. Have you tried it out after installing wireguard first?

**Comment by lupieczonka** [comment]
Hi my solution:
Post install wireguard test load modules
$ modprobe wireguard
FATAL: Module wireguard not found in directory
$ dkms status
$ dkms build wireguard/0.0.20200215
$ dkms install wireguard/0.0.20200215
$ modprobe wireguard
$  ip link add dev wg0 type wireguard
and start docker OK

**Comment by keremcankabadayi** [comment]
You just need to install Wireguard before running the container.

```
$ sudo add-apt-repository ppa:wireguard/wireguard
$ sudo apt-get update
$ sudo apt-get install wireguard
```

Then, you can create container.

**Comment by justperry** [comment]
Same problem here, but running docker from QNAP ContainerStation, installed Wireguard container first, think I will just put the config file from Wireguard in the config Folder, Thought the UI version would be easier, that is, if it ran.
