### ISSUE TITLE
Let us specifiy the endport address

### ISSUE THREAD

**Issue by UntouchedWagons** [EmbarkStudios/wg-ui#40]
**Is your feature request related to a problem? Please describe.**
Sort of. It seems this project is intended to be ran as a docker container and thus the endpoint address included in the config will invariably be wrong.

**Describe the solution you'd like**
A settings page including a textbox allowing me to manually specify the endpoint address or hostname.

**Describe alternatives you've considered**
Editing the config file then copying it over to my phone, tablet and laptop which is a bit of a faff.

**Additional context**
I dunno.

**Comment by cottley** [comment]
In the meantime, did you try running with the addition wg-endpoint flag --wg-endpoint="my.domain.com:51820"?
When doing a docker run anything "extra" at the command line is supposed to be used as an argument to the entrypoint binary. You can also add the argument in the dockerfile to set it to a default value.

Change 
ENTRYPOINT [ "/wireguard-ui" ]
to
ENTRYPOINT [ "/wireguard-ui", "--wg-endpoint='my.domain.com:51820'" ]
in the Dockerfile and see if that works for you.

**Comment by UntouchedWagons** [comment]
I did not as I had no way of knowing about that. That's not true exactly, I found out about that command line argument about five minutes ago through another bug report on this repository.

**Comment by suom1** [comment]
@UntouchedWagons did `--wg-endpoint` solve your problem?

**Comment by UntouchedWagons** [comment]
Yes
