### ISSUE TITLE
NAT cannot be disabled.

### ISSUE THREAD

**Issue by gdunstone** [EmbarkStudios/wg-ui#42]
trying to start with `--nat=false` results in:
> wireguard-ui: error: unexpected false, try --help

Try and run the server without NAT. It defaults to true if not specified and if specified and I cant negate it.

NAT should be disabled

I am running this in docker.

I am also trying to get some iptables rules working to forward traffic between clients, but I'm not particularly hopeful about that.

**Comment by suom1** [comment]
It should be --no-nat and not --nat=false

**Comment by gdunstone** [comment]
ahhh, ok. I see that now in the kingpin docs.
