### ISSUE TITLE
Need Help Starting / Buliding 

### ISSUE THREAD

**Issue by gtrdriver** [EmbarkStudios/wg-ui#59]
Hello

im new here - im Trying to folow the Build Instruction on a Debian Machine 
Starting Docker image is simple - also trying this:
`npm install --prefix=ui
npm run --prefix=ui dev`

Everything works fine

Trying to build i run into errors:
`go get -u github.com/go-bindata/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go-bindata-assetfs -prefix ui/dist ui/dist
go build .
sudo ./wireguard-ui --log-level=debug --dev-ui-server http://localhost:5000`

On  This command i get this error:

`axel@ubuntuvpn:/temp/wg-ui$ ./go-bindata-assetfs -prefix ui/dist ui/dist
-bash: ./go-bindata-assetfs: No such file or directory
`
If i go further then i get this on the next command:
`axel@ubuntuvpn:/temp/wg-ui$ sudo go build .
server.go:21:2: cannot find package "github.com/google/nftables" in any of:
        /usr/lib/go-1.10/src/github.com/google/nftables (from $GOROOT)
        /home/axel/go/src/github.com/google/nftables (from $GOPATH)
server.go:22:2: cannot find package "github.com/google/nftables/expr" in any of:
        /usr/lib/go-1.10/src/github.com/google/nftables/expr (from $GOROOT)
        /home/axel/go/src/github.com/google/nftables/expr (from $GOPATH)
server.go:23:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
        /usr/lib/go-1.10/src/github.com/julienschmidt/httprouter (from $GOROOT)
        /home/axel/go/src/github.com/julienschmidt/httprouter (from $GOPATH)
config.go:11:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)
        /home/axel/go/src/github.com/sirupsen/logrus (from $GOPATH)
server.go:25:2: cannot find package "github.com/skip2/go-qrcode" in any of:
        /usr/lib/go-1.10/src/github.com/skip2/go-qrcode (from $GOROOT)
        /home/axel/go/src/github.com/skip2/go-qrcode (from $GOPATH)
server.go:26:2: cannot find package "github.com/vishvananda/netlink" in any of:
        /usr/lib/go-1.10/src/github.com/vishvananda/netlink (from $GOROOT)
        /home/axel/go/src/github.com/vishvananda/netlink (from $GOPATH)
server.go:27:2: cannot find package "github.com/vishvananda/netns" in any of:
        /usr/lib/go-1.10/src/github.com/vishvananda/netns (from $GOROOT)
        /home/axel/go/src/github.com/vishvananda/netns (from $GOPATH)
server.go:28:2: cannot find package "golang.zx2c4.com/wireguard/wgctrl" in any of:
        /usr/lib/go-1.10/src/golang.zx2c4.com/wireguard/wgctrl (from $GOROOT)
        /home/axel/go/src/golang.zx2c4.com/wireguard/wgctrl (from $GOPATH)
config.go:12:2: cannot find package "golang.zx2c4.com/wireguard/wgctrl/wgtypes" in any of:
        /usr/lib/go-1.10/src/golang.zx2c4.com/wireguard/wgctrl/wgtypes (from $GOROOT)
        /home/axel/go/src/golang.zx2c4.com/wireguard/wgctrl/wgtypes (from $GOPATH)
main.go:7:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /usr/lib/go-1.10/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        /home/axel/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
`
Sorry - perhaps i misunderstood the Manual - please can anyone hlep me ?

**Comment by suom1** [comment]
This is due to you not having Go environment variables. I have updated the documentation to show what environment variables you need to build!
