### ISSUE TITLE
level=warning msg="Error parsing request: EOF" when trying to add a device

### ISSUE THREAD

**Issue by Sohalt** [EmbarkStudios/wg-ui#60]
**Describe the bug**
When trying to create add a new device using the lastest Docker image no device is added and I get the following error:
```
level=warning msg="Error parsing request: EOF" when trying to add a device
```

**To Reproduce**
1. `docker pull embarkstudios/wireguard-ui:latest`
2. `docker run -p 8080:8080 --privileged --rm -it -e WIREGUARD_UI_LOG_LEVEL=debug --entrypoint "/wireguard-ui" -v /tmp/wireguard-ui:/data  embarkstudios/wireguard-ui:latest`
3. go to `localhost:8080` and try to add a new device.

**Expected behavior**
A new device is added.

**Comment by suom1** [comment]
@spetzreborn Do you also have this issue in your setup?

**Comment by spetzreborn** [comment]
No, but have not run it in docker locally, same at work.
Is it running the latest of both the node app and the go backend?

**Comment by Sohalt** [comment]
I'm running the official image from Docker hub.
I think I found the issue. Since b471f3dff595f87166866bfe6c8eae4e1041b897 the image built by simply copying whatever is in the `ui/dist` directory, without actually building the frontend from source, so your changes didn't get picked up.
You'll either have to commit the build results in `ui/dist` or fix the Dockerfile to again build the ui from source.

**Comment by suom1** [comment]
> I think I found the issue:
> Since [b471f3d](https://github.com/EmbarkStudios/wg-ui/commit/b471f3dff595f87166866bfe6c8eae4e1041b897) the image is built by simply copying whatever is in the `ui/dist` directory, without actually building the frontend from source, so your changes didn't get picked up.
> You'll either have to commit the build results in `ui/dist` or fix the Dockerfile to again build the ui from source.

Good catch, lets put back the ui part into Dockerfile!
