### ISSUE TITLE
Help to understand how that should work 

### ISSUE THREAD

**Issue by tarek369** [EmbarkStudios/wg-ui#64]
I installed wire guard for Debian , and I have docker and I run now wireguard-ui on docker , when I use the config I see wrong ip and maybe port !
Do I need to configure something in wireguard before using wireguard-ui? Sorry I couldn't find any documentation

**Comment by suom1** [comment]
What settings have you tried starting wg-ui with? 
Have you checked the parameters from documentation? 

`--client-ip-range` needs to align with the IP network you have configured for wireguard under `[Interface]`

**Comment by tarek369** [comment]
I didn't configure wireguard !

**Comment by suom1** [comment]
> I didn't configure wireguard !

That's probably the reason then. Here is one [guide](https://www.linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/) that could work for you. I would advice you to google!
