### ISSUE TITLE
error make ui

### ISSUE THREAD

**Issue by jly26** [EmbarkStudios/wg-ui#69]
Hi , I have this error during make go binary
root@dns:~/wg-ui# make go-binary
go-bindata-assetfs -prefix ui/dist ui/dist
go build .
# github.com/google/nftables/expr
../go/pkg/mod/github.com/google/nftables@v0.0.0-20200316075819-7127d9d22474/expr/dynset.go:46:132: e.Timeout.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
Makefile:6: recipe for target 'go-binary' failed
make: *** [go-binary] Error 2

**Comment by suom1** [comment]
I have never seen that output. 
Have you done all needed steps that are found in the README?
Which platform do you build on? 

Tried building on Ubuntu 20.04 LTS and it worked fine. 
You can see what I did here: [pastebin.com](https://pastebin.com/dpKsvckJ) (Be aware that I have Go environment done, and node installed, you can also find that in the README)

**Comment by jly26** [comment]
I'm on debian 9.0 

https://pastebin.com/FFSYZ0gQ

**Comment by suom1** [comment]
Don't how your environment is setup, but I did just now do a test build on a fresh Debian 10, which worked fine. 

Here you can find a paste from that: [pastebin.com](https://pastebin.com/FFf3cHtt)

I doubt this is a bug in `wg-ui`

**Comment by jly26** [comment]
do I need to update  nodejs? 
root@dns:~/go/wg-ui# nodejs -v
v10.20.1
root@dns:~/go/wg-ui# go version
go version go1.14.3 linux/amd64

**Comment by suom1** [comment]
> do I need to update nodejs?
> root@dns:~/go/wg-ui# nodejs -v v10.20.1 root@dns:~/go/wg-ui# go version
> go version go1.14.3 linux/amd64

The error doesn't seem to be related to nodejs, so I doubt that you need to upgrade that. It seems to be related to Go.

**Comment by jly26** [comment]
Thank you ,updating  GO solves my issue..anyway how can I listening port?
INFO[0000] Starting
INFO[0000] WireGuard interface wg0 already exists. Reusing.
INFO[0000] Starting server                               listenAddr=":8080"
FATA[0000] listen tcp :8080: bind: address already in use
