### ISSUE TITLE
Not understanding how to get the Docker Arm version

### ISSUE THREAD

**Issue by alessandro-massarenti** [EmbarkStudios/wg-ui#71]
I tried running the docker container on my raspberry pi 4 but I get

`standard_init_linux.go:207: exec user process caused "exec format error"`

the usual error is thrown by the wrong architecture.

To resolve this problem I tried searching on older issues, and I found that 1.1.0 version has been compiled for arm, this said I see that the docker container has not been build for arm, is it possible to get one?

thank you in advance

**Comment by suom1** [comment]
That's correct, currently you need to create your own Dockerfile for arm. We've not taken final decision on which platforms we should support yet.

**Comment by alessandro-massarenti** [comment]
Oh, ok, good to know.

(Still thankful for you job)
