### ISSUE TITLE
A more convenience docker image.

### ISSUE THREAD

**Issue by m0ssc0de** [EmbarkStudios/wg-ui#82]
**Is your feature request related to a problem? Please describe.**
I notice several issues related to running `wg-ui` in a container. 
Some need more capabilities. Some were about updating kernel or managing kernel module security.
So could we have a more robust solution?

**Describe the solution you'd like**
Make a new docker image that includes a userspace Wireguard in it. This is for the people who think more about convenience than performance.

**Describe alternatives you've considered**
I have written a Dockerfile and entry point script for this solution, https://github.com/m0ssc0de/wg-ui/commit/80f5610d024db55fc4dcd4817ddc27110f2fb86b. Pre-build image, https://hub.docker.com/r/m0ssc0de/wg-go-ui. If everybody needs it, we could add it to `EmbarkStudios/wg-ui`.

**Additional context**
None

**Comment by suom1** [comment]
This is a nice suggestion.
Maybe it's time to figure out how we would do this the best way for ARM also and update docker hub to have them all in the same place. :)

**Comment by m0ssc0de** [comment]
> This is a nice suggestion.
> 
> Maybe it's time to figure out how we would do this the best way for ARM also and update docker hub to have them all in the same place. :) 


The image built on my Raspberry Pi looks pretty good. Where do you prefer to build image, Github action or an ARM buildkite agent? And does the ARM you said mean ARM64 or all version of ARM?

**Comment by suom1** [comment]
> The image built on my Raspberry Pi looks pretty good. Where do you prefer to build image, Github action or an ARM buildkite agent? And does the ARM you said mean ARM64 or all version of ARM?

I am at the moment working on a solution based on actions. Will include the PR here when it's done, and you can include your Dockerfile and script in same PR or create a new based on the setup.
