### ISSUE TITLE
Add flag for keepalive

### ISSUE THREAD

**Issue by Bouni** [EmbarkStudios/wg-ui#84]
**Is your feature request related to a problem? Please describe.**
As far as I can tell there is no flag that let me define a keepalive

**Describe the solution you'd like**
Add a flag, `--keepalive` for example that let me define my desired keepalive in seconds

**Comment by suom1** [comment]
What currently times out that would need an keepalive?

**Comment by Bouni** [comment]
Yes I was referning to the `PersistentKeepalive`in the client config!

**Comment by suom1** [comment]
Hmm, yeah why not. We could do it the same way we do with dns-resolvers!

**Comment by Bouni** [comment]
Yes, thats what i had in mind. My Go knowledge is just to minimal to provide a PR 🤷‍♂️

**Comment by Bouni** [comment]
Thanks for adding this feature request so quickly!
