### ISSUE TITLE
Question: UI in Docker and Wireguard in VM

### ISSUE THREAD

**Issue by IosifZ** [EmbarkStudios/wg-ui#98]
Hi all,

Here is my setup:
Docker for Windows installed on a Windows 10 Pro OS
Linux Mint Hyper-V VM acting as DNS (PieHole and DOH)
Kubuntu Hyper-V VM (used for a previous Wireguard installation with a deprecated UI)

I was looking for a simple Wireguard WEB UI and I stumbled on this lovely project.
I've found other alternatives (not too many out there) but I need something very simple, https, certs and other stuff are not needed. I just want a web UI for Wireguard, that can manage the server, generate configs and leverage the use of QR code for my phone.

As nor Linux or terminal aren't my strong skills, this is what I am planning on doing, hoping that you can tell me if this solution would work or not.

Install the Wireguard VPN server on the Kubuntu VM.
Install wg-ui in Docker and using it to manage the Wireguard server from the VM.

The VM already has it's own IP already and I would run the wg-ui web portal through my existing reverse proxy (Traefik) with SSO (Google).

Would this work ?

**Comment by suom1** [comment]
I do not see why it wouldn't work. In our setup we use a instance of nginx which does SSO-proxy and reverse-proxying with SSL.

**Comment by IosifZ** [comment]
> I do not see why it wouldn't work. In our setup we use a instance of nginx which does SSO-proxy and reverse-proxying with SSL.

What if the Docker installation is on the Windows 10 machine and the Wireguard one is on a Linux VM ?
